---
- hosts: all
  become: true
  pre-tasks:

  - name: install updates
    package:
      upgrade: dist
      update_cache: yes
      # doesn't count as change:
      changed_when: false

- hosts: Avell_in_Popoloninnis
  become: true
  connection: local
  var:
    package_names:
      - python3-psutil
      - htop
      - tmux
      - neovim
      - mixxx
      - ninja-build
      - wine
      - cmake
      - make
      - gcc
      - git
      - qt5-default
      - libudev-dev
      - build-essential
      - libjack-jackd2-dev
      - libsndfile1-dev
      - libfftw3-dev
      - libxt-dev
      - libavahi-client-dev
      - libasound2-dev
      - libicu-dev
      - libreadline6-dev
      - libudev-dev
      - pkg-config
      - libncurses5-dev

  tasks:

  - name: install packages
    tags: livecoding
    package:
      name:
      state: latest
    # when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: copy wallpaper file
    copy:
      src: files/wallpaper.png
      dest: /usr/share/backgrounds/vim_cheatsheet.png
      owner: root
      group: root

  - name: set wallpaper
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/vim_cheatsheet.png'"

  - name: set wallpaper position
    dconf:
      become_user: skmecs 
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"

  - name: add ansible user
    tags: always
    user:
      name: exu
      system: yes

  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_exu
      dest: /etc/sudoers.d/exu
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: exu
      minute: "*/10"
      job: ansible-pull -o -U "https://github.com/gilfuser/ansible_laptop.git"



